### ISSUE TITLE
Laser Bug

### ISSUE THREAD

**Issue by ghost** [Teetime/teeworlds#2]
Occasionally, the laser would bug out and not shoot, well passed the reload time. This happens multiple times in one round so it does get quite annoying.

**Comment by Teetime** [comment]
I never saw the bug which you describe. Do you have some further information? For example which gametype, maybe at what situation (are you doing something special before?), serversettings etc.

**Comment by ghost** [comment]
I will pay more attention to the circumstances whenever it occurs, but from what it looks like it is quite arbitrary and nothing sticks out. I'll look into doing a fraps video, so you can see for yourself. Could the hook settings have anything to do with it?

Here is my config which has all the settings information:
#Important server settings
sv_name
console_output_level 2
logfile 7_27_06_2012.txt
sv_bindaddr 
sv_port 
sv_tournament_mode 0
sv_register 1
sv_high_bandwidth 0
sv_gametype zCatch
sv_max_clients 16
sv_max_clients_per_ip 3

#Rcon settings
sv_rcon_max_tries 3
sv_rcon_bantime 5
sv_rcon_password 
sv_rcon_mod_password 

#Privilages
mod_command shutdown 1
mod_command reset 1
mod_command restart 1
mod_command sv_map 2
mod_command status 1
mod_command mute 1
mod_command mutes 1
mod_command muteid 1
mod_command muteip 1
mod_command kick 1
mod_command ban 1
mod_command bans 1
mod_command logout 1

#zcatch settings
sv_mode 1
sv_allow_join 2
sv_color_indicator 1
sv_bonus 0
sv_follow_catcher 1
sv_vote_forcereason 1
sv_laserjumps 0
sv_grenade_min_damage 4
sv_suicide_time 0
sv_kill_penalty 5
sv_scorelimit 150

#Mute on spam 
sv_chat_value 250  
sv_chat_threshold 1000
sv_mute_duration 15

#Anticamper
sv_anticamper 2
sv_anticamper_freeze 7

#!!I recommend not to change these variables, except you know what you do!!  
sv_anticamper_time 10
sv_anticamper_range 380

#What to do with an inactive
sv_inactivekick 1
sv_inactivekick_time 5

#Spectator Options
sv_spectator_slots 0
sv_strict_spectate_mode

#vote options
sv_vote_kick 1
sv_vote_kick_bantime 5
sv_vote_spectate 0

#announcement options
sv_announcement_interval 5
sv_announcement_filename announcement.txt
sv_announcement_random 1

#Map server starts with
sv_map ctf5_new

#Important server tunes, must not be changed.
tune hook_length 100000
tune hook_fire_speed 1000
tune hook_drag_speed 40
sv_kill_penalty 0

#server callvote list, mainly for maps
add_vote "ctf5_new" sv_map ctf5_new
add_vote "ctf2" sv_map ctf2
add_vote "ctf3" sv_map ctf3

**Comment by Teetime** [comment]
Well I never saw it and I never got any reports of such a bug. Maybe this occurs when the server is online for a long time but this is a client bug, see issue #1157 in the teeworlds-repo
