### ISSUE TITLE
Add some documentation for TW+

### ISSUE THREAD

**Issue by hydroid7** [Teetime/teeworlds#5]
In the forum [https://www.teeworlds.com/forum/viewtopic.php?id=9431](TWForum)  you can find any informations to this mod. 

Would it possible to write them in the Readme file? Would more easier to find. 
I would create a Pull Request if you are agreeing with me.

**Comment by Teetime** [comment]
I added some things into the readme.md, but they are basically the same things as in the teeworlds topic. If you have more ideas what I should add, feel free to mention them :)

**Comment by hydroid7** [comment]
THX that was my idea too. ;-)
Am 26.03.2016 10:07 schrieb "Teetime" notifications@github.com:
